name: open_museum_guide
description: Open museum guide - Augmented reality guide for famous paintings in museums

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  tflite:
    git: https://github.com/nesarares/flutter_tflite
  
  cupertino_icons: ^0.1.2
  feather_icons_flutter: ^4.7.4
  fluttertoast: ^3.0.1
  flushbar: ^1.4.0

  after_layout: ^1.0.7
  path_provider: ^0.5.0+1
  archive: ^2.0.8
  flutter_downloader: ^1.1.7
  cloud_firestore: ^0.9.10
  firebase_storage: ^2.1.0+1
  sqflite: ^1.1.3
  rxdart: ^0.21.0
  
  image_picker: ^0.5.2
  image: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.0"
  
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon/icon.png'


# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/museum.png
    - assets/images/orsay.jpg
    - assets/images/louvre.jpg
    - assets/images/loading.png
    - assets/graph/paintings.tflite
    - assets/graph/paintings.txt

  fonts:
    - family: Rufina
      fonts:
        - asset: assets/fonts/Rufina-Regular.ttf
        - asset: assets/fonts/Rufina-Bold.ttf
          weight: 700
    - family: Varela Round
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900