name: open_museum_guide
description: Open museum guide - Augmented reality guide for famous paintings in museums

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^0.4.5

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/museum.png
   - assets/images/orsay.jpg
   - assets/images/louvre.jpg

  fonts:
    - family: Rufina
      fonts:
        - asset: assets/fonts/Rufina-Regular.ttf
        - asset: assets/fonts/Rufina-Bold.ttf
          weight: 700
    - family: Varela Round
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700